//
//  UserTests.swift
//  PaperlessAPI
//
//  Created by Leo Wehrfritz on 13.12.24.
//

import Testing
import Foundation
@testable import PaperlessAPI

@Test func decodeUser() async throws {
    
    let json = """
{
      "id": 3,
      "username": "demo",
      "email": "demo@paperparrot.me",
      "password": "**********",
      "first_name": "Demo",
      "last_name": "User",
      "date_joined": "2023-02-20T10:06:34.690615+01:00",
      "is_staff": true,
      "is_active": true,
      "is_superuser": true,
      "groups": [],
      "user_permissions": [
        "add_logentry",
        "change_logentry",
        "delete_logentry",
        "view_logentry",
        "add_group",
        "change_group",
        "delete_group",
        "view_group",
        "add_user",
        "change_user",
        "delete_user",
        "view_user",
        "add_correspondent",
        "change_correspondent",
        "delete_correspondent",
        "view_correspondent",
        "add_customfield",
        "change_customfield",
        "delete_customfield",
        "view_customfield",
        "add_document",
        "change_document",
        "delete_document",
        "view_document",
        "add_documenttype",
        "change_documenttype",
        "delete_documenttype",
        "view_documenttype",
        "add_note",
        "change_note",
        "delete_note",
        "view_note",
        "add_paperlesstask",
        "change_paperlesstask",
        "delete_paperlesstask",
        "view_paperlesstask",
        "add_savedview",
        "change_savedview",
        "delete_savedview",
        "view_savedview",
        "add_sharelink",
        "change_sharelink",
        "delete_sharelink",
        "view_sharelink",
        "add_storagepath",
        "change_storagepath",
        "delete_storagepath",
        "view_storagepath",
        "add_tag",
        "change_tag",
        "delete_tag",
        "view_tag",
        "add_uisettings",
        "change_uisettings",
        "delete_uisettings",
        "view_uisettings",
        "add_workflow",
        "change_workflow",
        "delete_workflow",
        "view_workflow",
        "add_applicationconfiguration",
        "change_applicationconfiguration",
        "delete_applicationconfiguration",
        "view_applicationconfiguration",
        "add_mailaccount",
        "change_mailaccount",
        "delete_mailaccount",
        "view_mailaccount",
        "add_mailrule",
        "change_mailrule",
        "delete_mailrule",
        "view_mailrule"
      ],
      "inherited_permissions": [
        "documents.delete_savedviewfilterrule",
        "documents.delete_comment",
        "account.delete_emailconfirmation",
        "socialaccount.change_socialaccount",
        "documents.add_workflow",
        "django_celery_results.change_chordcounter",
        "documents.change_customfieldinstance",
        "documents.add_uisettings",
        "documents.view_customfield",
        "guardian.change_groupobjectpermission",
        "auditlog.delete_logentry",
        "documents.add_customfield",
        "documents.delete_tag",
        "auth.view_user",
        "sessions.delete_session",
        "documents.delete_customfield",
        "documents.delete_customfieldinstance",
        "documents.add_documenttype",
        "auditlog.view_logentry",
        "django_celery_results.add_taskresult",
        "sessions.add_session",
        "auth.add_group",
        "contenttypes.view_contenttype",
        "paperless_mail.delete_processedmail",
        "documents.delete_savedview",
        "documents.change_paperlesstask",
        "documents.change_document",
        "documents.view_paperlesstask",
        "socialaccount.add_socialtoken",
        "auth.delete_group",
        "account.add_emailconfirmation",
        "paperless_mail.view_mailaccount",
        "documents.view_tag",
        "documents.delete_workflow",
        "paperless_mail.add_processedmail",
        "documents.add_tag",
        "documents.change_savedviewfilterrule",
        "documents.delete_documenttype",
        "documents.delete_uisettings",
        "documents.view_savedviewfilterrule",
        "auditlog.add_logentry",
        "account.add_emailaddress",
        "paperless_mail.delete_mailaccount",
        "guardian.change_userobjectpermission",
        "documents.view_savedview",
        "socialaccount.delete_socialaccount",
        "auth.add_permission",
        "socialaccount.change_socialapp",
        "documents.add_document",
        "documents.change_correspondent",
        "authtoken.view_tokenproxy",
        "documents.add_workflowaction",
        "account.view_emailconfirmation",
        "documents.change_savedview",
        "django_celery_results.delete_groupresult",
        "account.change_emailaddress",
        "django_celery_results.add_groupresult",
        "documents.view_workflowtrigger",
        "documents.add_savedview",
        "django_celery_results.delete_taskresult",
        "documents.change_sharelink",
        "documents.change_storagepath",
        "documents.change_note",
        "documents.delete_correspondent",
        "documents.change_tag",
        "paperless_mail.add_mailrule",
        "documents.delete_paperlesstask",
        "paperless_mail.view_mailrule",
        "documents.add_sharelink",
        "django_celery_results.change_taskresult",
        "auth.delete_permission",
        "account.view_emailaddress",
        "documents.view_document",
        "documents.add_comment",
        "documents.add_note",
        "documents.change_workflowaction",
        "documents.change_workflowtrigger",
        "auth.delete_user",
        "documents.change_workflow",
        "guardian.view_userobjectpermission",
        "documents.add_customfieldinstance",
        "authtoken.change_tokenproxy",
        "documents.add_correspondent",
        "guardian.add_groupobjectpermission",
        "documents.add_savedviewfilterrule",
        "documents.view_storagepath",
        "documents.change_documenttype",
        "paperless.add_applicationconfiguration",
        "admin.change_logentry",
        "socialaccount.view_socialaccount",
        "documents.change_uisettings",
        "django_celery_results.delete_chordcounter",
        "auth.view_permission",
        "paperless.change_applicationconfiguration",
        "auditlog.change_logentry",
        "guardian.delete_userobjectpermission",
        "django_celery_results.view_chordcounter",
        "documents.change_customfield",
        "account.change_emailconfirmation",
        "documents.delete_document",
        "guardian.add_userobjectpermission",
        "admin.delete_logentry",
        "documents.change_comment",
        "documents.view_documenttype",
        "documents.delete_log",
        "documents.delete_workflowaction",
        "socialaccount.add_socialapp",
        "paperless_mail.change_mailaccount",
        "authtoken.delete_token",
        "paperless.view_applicationconfiguration",
        "guardian.delete_groupobjectpermission",
        "socialaccount.change_socialtoken",
        "admin.add_logentry",
        "paperless.delete_applicationconfiguration",
        "documents.delete_sharelink",
        "auth.view_group",
        "socialaccount.delete_socialapp",
        "django_celery_results.change_groupresult",
        "sessions.view_session",
        "paperless_mail.change_mailrule",
        "paperless_mail.change_processedmail",
        "auth.change_permission",
        "socialaccount.add_socialaccount",
        "documents.delete_note",
        "auth.add_user",
        "documents.view_customfieldinstance",
        "documents.view_sharelink",
        "documents.view_workflowaction",
        "paperless_mail.view_processedmail",
        "contenttypes.change_contenttype",
        "documents.add_workflowtrigger",
        "documents.view_workflow",
        "documents.delete_storagepath",
        "authtoken.change_token",
        "documents.delete_workflowtrigger",
        "documents.add_paperlesstask",
        "documents.add_log",
        "documents.view_log",
        "contenttypes.delete_contenttype",
        "socialaccount.view_socialtoken",
        "guardian.view_groupobjectpermission",
        "django_celery_results.view_groupresult",
        "authtoken.delete_tokenproxy",
        "django_celery_results.add_chordcounter",
        "socialaccount.view_socialapp",
        "paperless_mail.delete_mailrule",
        "django_celery_results.view_taskresult",
        "account.delete_emailaddress",
        "documents.view_note",
        "documents.view_comment",
        "documents.view_uisettings",
        "documents.change_log"
      ]
    }
""".data(using: .utf8)!
    
    
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .paperlessDateFormat
    let user = try decoder.decode(User.self, from: json)
    
    #expect(user.id == 3)
    #expect(user.username == "demo")
    #expect(user.password == "**********")
    #expect(user.email == "demo@paperparrot.me")
    #expect(user.firstName == "Demo")
    #expect(user.lastName == "User")
    #expect(user.isStaff)
    #expect(user.isActive)
    #expect(user.isSuperuser)
    #expect(user.groups.isEmpty)
    #expect(user.userPermissions.count == 72)
    user.userPermissions.forEach { permission in
        if case .unknown = permission {
            Issue.record("Couldn't decode permission: \(permission.rawValue)")
        }
    }
    user.inheritedPermissions.forEach { permission in
        if case .unknown = permission {
            Issue.record("Couldn't decode permission: \(permission.rawValue)")
        }
    }
    #expect(user.inheritedPermissions.count == 152)
}
